openapi: 3.0.0
info:
  title: Notificatie API - Publish Notification
  description: '
    API to publish a notification.
    Work in progress, can change completely without notice.

    Standards
    * [GOV NL API Design Rules](https://publicatie.centrumvoorstandaarden.nl/api/adr/#normative-design-rules)
    * [GOV NL profile for CloudEvents](https://Logius-standaarden.github.io/NL-GOV-profile-for-CloudEvents).'
  license:
    name: EUPL 1.2
    url: https://opensource.org/licenses/EUPL-1.2
  version: 0.0.1 - Work in progress
security:
- JWT-Claims: []
paths:
  /notifications:
    post:
      operationId: publish_notification
      description: Publish a notification.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/notification'
        required: true
      responses:
        # to do: define responses
        '200':
          description: ''
          headers:
            API-version:
              schema:
                type: string
              description: 'API-version in the context of the call. Example: 1.2.1.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notification'
      tags:
      - notifications
      security:
      - JWT-Claims:
        - notifications.distribute
    parameters: []
servers:
- url: /api/v1
components:
  securitySchemes:
    JWT-Claims:
      bearerFormat: JWT
      scheme: bearer
      type: http
  schemas:
    notification:
      required:
      - id
      - source
      - type
      type: object
      properties:
        id:
          title: id
          description: Identifies the event.
          type: string
          format: uuid
          example: '2febb675-b06c-4f3a-8fc3-f6649aa25ae4'
        source:
          title: source
          description: Identifies the context in which an event happened.
          type: string
          format: urn
          example: 'urn:nld:oin:00000001234567890000:systeem:BronX'
        type:
          title: type
          description: This attribute contains a value describing the type of event related to the originating occurrence.
          type: string
          format: reverse dns
          example: 'nl.brp.verhuizing_geregistreerd'
        typeUrl:
          title: typeUrl
          description: Reference to more information about the type.
          type: string
          format: uri
          example: 'www.brp.nl/eventtypes/verhuizing_geregistreerd/v1.0'
        subject:
          title: subject
          description: This describes the subject of the event in the context of the event producer (identified by source).
          type: string
          minLength: 1
          maxLength: 50
          example: 'nl.brp.persoon'
        time:
          title: time
          description: Timestamp of when the occurrence happened.
          type: string
          format: date-time
          example: '2021-08-16T15:29:30.833664Z'
        datacontenttype:
          title: datacontenttype
          description: Content type of data value.
          type: string
          example: 'application/json'
        dataschema:
          title: dataschema
          description: Identifies the schema that data adheres to.
          type: string
          example: 'nl.brp.persoon.adres'
        data:
          title: data
          description: As defined by the term Data, CloudEvents MAY include domein-specific information about the occurrence. When present, this information will be encapsulated within data.
          type: object
        dataref:
          title: dataref
          description: A reference to a location where the event payload is stored.
          type: string
          format: uri
          example: 'www.brp.nl/gebeurtenissen/2febb675-b06c-4f3a-8fc3-f6649aa25ae4'
        sequence:
          title: sequence
          description: Value expressing the relative order of the event. This enables interpretation of data supercedence.
          type: string
          example: '42'
        sequencetype:
          title: sequencetype
          description: Specifies the semantics of the sequence attribute.
          type: string
          example: 'integer'
