openapi: 3.0.0
info:
  title: Notificatie API - Data schema
  description: '
    Suggestion for data schema
    Work in progress, can change completely without notice.

    Standards
    * [GOV NL API Design Rules](https://publicatie.centrumvoorstandaarden.nl/api/adr/#normative-design-rules)
    * [GOV NL profile for CloudEvents](https://vng-realisatie.github.io/NL-GOV-profile-for-CloudEvents).'
  license:
    name: EUPL 1.2
    url: https://opensource.org/licenses/EUPL-1.2
  version: 0.0.1 - Work in progress
components:
  schemas:
    notificationData:
      type: object
      properties:
        identification:
          title: identification
          description: Identification of subjects/objects
          type: object
          additionalProperties:
            title: id
            description: Value of the id
            type: string
            maxLength: 40
            minLength: 1
        properties:
          title: properties
          description: Properties of the event can be used for filtering
          type: object
          additionalProperties:
            title: property
            description: Value of the property
            type: string
            maxLength: 1000
            minLength: 1
        eventdata:
          title: eventdata
          description: Event data
          type: object
